### ISSUE TITLE
Agent dying on startup when not passing an argument

### ISSUE THREAD

**Issue by y0k4i-1337** [Ne0nd0g/merlin-agent#8] opened 2022-02-28 01:38 UTC
### Prerequisite

* [x] I have searched the opened & _closed_ [issues](https://github.com/Ne0nd0g/merlin-agent/issues)
* [x] I have searched the [WIKI](https://merlin-c2.readthedocs.io/en/latest/index.html) and its [FAQ](https://merlin-c2.readthedocs.io/en/latest/quickStart/faq.html) page

### Environment Data

* Merlin Version: 1.3.0
* Merlin Build: e89a29d99a3cea7d02d28672290f5fdb2cc60d99
* Go Version: 1.16.10
* GOPATH Environment Variable: ~/go
* GOROOT Environment Variable: ~/.asdf/installs/golang/1.16.10/go
* Operating System: Linux 

### Expected Behavior
The agent runs even without any argument being passed, according to how it was built.

### Actual Behavior
When not passing an argument, the agent is dying and showing an error on screen.
The error presented on agent side:
```
./bin/v1.3.0/e89a29d99a3cea7d02d28672290f5fdb2cc60d99/merlinAgent

panic: send on closed channel

goroutine 20 [running]:
main.getArgsFromStdIn(0xc0000c6480)
	~/merlin-agent/main.go:172 +0x65
created by main.main
	~/merlin-agent/main.go:80 +0xc2a
```

### Steps to Reproduce Behavior
Compiled with
```
make linux MAXRETRY=30 PROTO=http3 SLEEP=30s URL=https://127.0.0.1:10443
```
Ran the agent without any argument:
```
./bin/v1.3.0/e89a29d99a3cea7d02d28672290f5fdb2cc60d99/merlinAgent
```

### Misc Information
If I run the agent with some argument, like `-debug`, it is able to connect to server without error.

**Comment by Ne0nd0g** [comment] 2022-02-28 02:04
@yok4i I tried this with Go 1.16.3 doing a fresh clone and build the way you did and everything worked without error. I'm going to try again with go 1.16.10.

What are the RAM and CPU resources where the agent is running? What is the output of `go env`

**Comment by Ne0nd0g** [comment] 2022-02-28 02:21
The agent ran without error using go1.16.10. As a workaround you can comment out the `getArgsFromStdIn` function on line 80 in main.go. What Linux distribution are you running the agent on?

**Comment by y0k4i-1337** [comment] 2022-02-28 02:42
Hi, @Ne0nd0g. Thanks for the reply.
My envs are as follows:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/user/.asdf/installs/golang/1.16.10/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/user/.asdf/installs/golang/1.16.10/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.10"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/git/merlin-agent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3474138602=/tmp/go-build -gno-record-gcc-switches"
```
The agent is running on a `Pop!_OS 21.10` system with a hardware configuration of 16GB RAM and Intel i5 10th gen. I tried running in other terminal apps and with different shells and the error persisted.
Commenting out the offending go routine makes the agent runs normally.

**Comment by Ne0nd0g** [comment] 2022-03-01 13:20
@yok4i I did a fresh install of Pop! OS, did a fresh git clone of Merlin, compiled it with Go 1.16.10, and ran the agent without error. I'm unable to reproduce the original issue. Are you able to reproduce the error on any other hosts? Any last ideas for. how. I can reproduce the issue for I close this issue?

![image](https://user-images.githubusercontent.com/5638474/156176248-a522d98a-a91a-43f6-aca7-37f9c0852977.png)
![image](https://user-images.githubusercontent.com/5638474/156176311-8dcc8023-24db-4e42-afc7-511f218864bc.png)

**Comment by y0k4i-1337** [comment] 2022-03-03 01:13
Man, I have no idea what's going on. It must be something very particular to my installation/hardware. Very weird lol
You may close this issue for sure. Thanks for all your support on this.

**Closed as completed** 2022-03-03 01:30 UTC
